// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw1GE5xi4UoM-sDd1n8VSg8fsliPntwxI',
    appId: '1:15841456633:web:e926de8134a16a8d87cd28',
    messagingSenderId: '15841456633',
    projectId: 'hane-73789',
    authDomain: 'hane-73789.firebaseapp.com',
    storageBucket: 'hane-73789.appspot.com',
    measurementId: 'G-WXQT1R2ZRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBma7jWfpWnJSTUS_762oJimM5sp1Cm5OU',
    appId: '1:15841456633:android:e4e95ede0eadb93c87cd28',
    messagingSenderId: '15841456633',
    projectId: 'hane-73789',
    storageBucket: 'hane-73789.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwdBR5avlmRGfBXwDOAiYWWxHZnw1PlmQ',
    appId: '1:15841456633:ios:579519159159161487cd28',
    messagingSenderId: '15841456633',
    projectId: 'hane-73789',
    storageBucket: 'hane-73789.appspot.com',
    iosBundleId: 'com.example.hane',
  );

}